import type { Metadata } from 'next'
import './globals.css'
import {cms} from '@/cms'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
      <cms.previews />
    </html>
  )
}
